[package]
name = "exbio"
version = "0.1.0"
authors = []

[lib]
name = "exbio"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.21.0"
rustler_codegen = "0.21.0"
bio = "0.30.0"
bio-types = ">=0.5.1"
lazy_static = "1.4"
